// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __BLE_CALLBACKS__
#define __BLE_CALLBACKS__


#endif // __BLE_CALLBACKS__
