// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __MPSI_CONFIGURATION__
#define __MPSI_CONFIGURATION__


// Generated message IDs

// Generated function mapping
#define MPSI_GENERATED_FUNCTION_MAP \
{\
}

#endif // __MPSI_CONFIGURATION__
